#!/bin/env zsh

# ls colors
autoload -U colors && colors
export LSCOLORS="GxFxcxdxbxegedabagacad"
export CLICOLOR=1

ls --color -d . &>/dev//null 2>&1 && alias ls='ls --color=tty' || alias ls='ls -G'



