# Load common config
for cfgFile in $DOTFILE_DIR/system/configs/*.zsh; do
    source $cfgFile
done

# Load local zshrc
# - all local config overrides will go in here
[ -f $DOTFILE_LOCAL_DIR/zshrc.local ] && source $DOTFILE_LOCAL_DIR/zshrc.local

